-- Create core schemas
CREATE DATABASE IF NOT EXISTS RISK_COPILOT_DB;
CREATE SCHEMA IF NOT EXISTS RISK_COPILOT_DB.COMPLIANCE_CORE;
USE SCHEMA RISK_COPILOT_DB.COMPLIANCE_CORE;

-- 1. Create Identity Access Master Table
CREATE OR REPLACE TABLE IDENTITY_ACCESS_MASTER (
    USER_ID INT IDENTITY(1,1),
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    ACCESS_ROLE VARCHAR(50),
    CLEARANCE_LEVEL VARCHAR(30),
    PASSWORD VARCHAR(50), -- Matching text-based lookup configurations
    DEPARTMENT VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Insert initial hackathon user credentials profiles
INSERT INTO IDENTITY_ACCESS_MASTER (USERNAME, DISPLAY_NAME, ACCESS_ROLE, CLEARANCE_LEVEL, PASSWORD, DEPARTMENT)
VALUES 
('jclerk01', 'Ravi Menon', 'JUNIOR_CLERK', 'L1_BASIC', 'clerk@2026', 'Operations Ledger'),
('cofficer01', 'Meera Iyer', 'COMPLIANCE_OFFICER', 'L2_ELEVATED', 'comply@2026', 'Regulatory Audit'),
('ppco01', 'Arjun Deshmukh', 'PRINCIPAL_PCO', 'L3_RESTRICTED', 'principal@2026', 'Risk Containment'),
('sysadmin01', 'Appala Srinivas Tanakala', 'SYSTEM_ADMIN', 'L4_FULL_ACCESS', 'admin@2026', 'IT Security & IAM');

-- 2. Create Remediation Logging Matrix Table
CREATE OR REPLACE TABLE REMEDIATION_LOG (
    LOG_ID INT IDENTITY(1,1),
    ACCOUNT_ID VARCHAR(50),
    SYSTEMIC_LOCK_STATUS VARCHAR(30),
    OUTBOUND_OVERRIDE_ENABLED BOOLEAN,
    KYC_STEP_UP_LEVEL VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    COMPLIANCE_REMARKS TEXT,
    DOCUMENT_REFERENCE VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Create Account Master Table
CREATE OR REPLACE TABLE ACCOUNT_MASTER (
    ACCOUNT_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    KYC_STATUS VARCHAR(30), -- 'Verified', 'Pending', 'Suspended'
    CUSTOMER_TYPE VARCHAR(50),
    IS_PEP BOOLEAN DEFAULT FALSE,
    RISK_TIER VARCHAR(10),
    IEC_CODE VARCHAR(50),
    TRADE_LICENSE_TYPE VARCHAR(100),
    PRIMARY_TRADE_ROLE VARCHAR(100),
    AUTHORIZED_AD_BANK VARCHAR(100),
    CURRENT_BALANCE_INR NUMBER(18,2),
    GSTIN VARCHAR(50),
    TAX_IDENTIFIER VARCHAR(50), -- PAN Card
    PERMANENT_ADDRESS TEXT,
    REGISTRATION_DATE DATE,
    LAST_AUDIT_DATE DATE
);

-- 4. Create Transaction Ledger Table
CREATE OR REPLACE TABLE TRANSACTION_LEDGER (
    TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(50),
    AMOUNT_INR NUMBER(18,2),
    DESTINATION_COUNTRY_ISO VARCHAR(10),
    TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 5. Create AML Regulatory Policies Table (with Vector Support)
CREATE OR REPLACE TABLE AML_REGULATORY_POLICIES (
    POLICY_ID INT IDENTITY(1,1),
    RULE_TEXT TEXT,
    RULE_VECTOR VECTOR(FLOAT, 768) -- Matches 'e5-base-v2' embedding space
);

-- 6. Create Sanctions Watchlist Table
CREATE OR REPLACE TABLE SANCTIONS_WATCHLIST (
    WATCHLIST_ID INT IDENTITY(1,1),
    COUNTRY_ISO VARCHAR(10),
    RISK_LEVEL VARCHAR(30),
    REASON TEXT
);

-- 7. Create Trade Shipments Table
CREATE OR REPLACE TABLE TRADE_SHIPMENTS (
    SHIPMENT_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(50),
    GOODS_DESCRIPTION TEXT,
    DECLARED_VALUE_INR NUMBER(18,2)
);

-- 8. Create the Missing Core View
CREATE OR REPLACE VIEW COMPLIANCE_AUDIT_STREAM AS
SELECT 
    t.TRANSACTION_ID,
    t.ACCOUNT_ID,
    a.CUSTOMER_NAME,
    t.AMOUNT_INR,
    t.DESTINATION_COUNTRY_ISO,
    t.TRANSACTION_TIMESTAMP,
    a.KYC_STATUS,
    a.IS_PEP,
    CASE 
        WHEN t.AMOUNT_INR >= 5000000 THEN 'HIGH_VALUE_THRESHOLD_ALERT'
        ELSE 'SUSPICIOUS_VELOCITY_ALERT'
    END AS RISK_SIGNAL
FROM TRANSACTION_LEDGER t
JOIN ACCOUNT_MASTER a ON t.ACCOUNT_ID = a.ACCOUNT_ID;
