```sql
-- Create core schemas
CREATE DATABASE IF NOT EXISTS RISK_COPILOT_DB;
CREATE SCHEMA IF NOT EXISTS RISK_COPILOT_DB.COMPLIANCE_CORE;
USE SCHEMA RISK_COPILOT_DB.COMPLIANCE_CORE;

-- 1. Create Identity Access Master Table
CREATE OR REPLACE TABLE IDENTITY_ACCESS_MASTER (
    USER_ID INT IDENTITY(1,1),
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    ACCESS_ROLE VARCHAR(50),
    CLEARANCE_LEVEL VARCHAR(30),
    PASSWORD VARCHAR(50), -- Matching text-based lookup configurations
    DEPARTMENT VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Insert initial hackathon user credentials profiles
INSERT INTO IDENTITY_ACCESS_MASTER (USERNAME, DISPLAY_NAME, ACCESS_ROLE, CLEARANCE_LEVEL, PASSWORD, DEPARTMENT)
VALUES 
('jclerk01', 'Ravi Menon', 'JUNIOR_CLERK', 'L1_BASIC', 'clerk@2026', 'Operations Ledger'),
('cofficer01', 'Meera Iyer', 'COMPLIANCE_OFFICER', 'L2_ELEVATED', 'comply@2026', 'Regulatory Audit'),
('ppco01', 'Arjun Deshmukh', 'PRINCIPAL_PCO', 'L3_RESTRICTED', 'principal@2026', 'Risk Containment'),
('sysadmin01', 'Appala Srinivas Tanakala', 'SYSTEM_ADMIN', 'L4_FULL_ACCESS', 'admin@2026', 'IT Security & IAM');

-- 2. Create Remediation Logging Matrix Table
CREATE TABLE IF NOT EXISTS REMEDIATION_LOG (
    LOG_ID INT IDENTITY(1,1),
    ACCOUNT_ID VARCHAR(50),
    SYSTEMIC_LOCK_STATUS VARCHAR(30),
    OUTBOUND_OVERRIDE_ENABLED BOOLEAN,
    KYC_STEP_UP_LEVEL VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    COMPLIANCE_REMARKS TEXT,
    DOCUMENT_REFERENCE VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
